### ISSUE TITLE
Software Architecture Planning

### ISSUE THREAD

**Issue by koscinskic** [GatorCogitate/cogitate_tool#15]
I've opened this issue for the software architecture leaders of each team so we can discuss how to proceed in the future when integrating our individual features into the repository.

Currently, the only standards I would like to set forth are to organize the highest-level functions and methods by this format:

```
@api_app.fxn("/function_name")
def function_name(input_value):
    # Code Content
    return return_value
```

At the very least, if we can agree to keeping our input and output values as primitive as possible, it will make developing and integrating a more cohesive structure easier in the future (e.g. if your feature only necessitates the retrieval of data, then return that data with as few alterations as possible. If your feature visualizes data, ensure the original data set remains unaltered, etc.)

**Comment by koscinskic** [comment]
Moving forward, we should decide here on how we are going to localize and store data. I've had a good amount of experience with anything pertaining to .csv files, but .json files are a more popular standard. Anyone have any alternative suggestions / thoughts?

**Comment by carmop** [comment]
I talked to the TAs after class yesterday and we've thought that .json would be better. But it also depends on the tools we are using, I have not looked at PyDriller and PyGitHub but if they give us data in .json format it would be better to just keep it as .json. That being said I do not have a lot of experience with either.

**Comment by mcnultycollin** [comment]
https://blog.datafiniti.co/4-reasons-you-should-use-json-instead-of-csv-2cac362f1943
^ this points to using json. 

Also, considering the lecture in class today about using Python as Object-Oriented, Procedural, or Functional, should we consider picking one of those as our guiding principle for the project? Maybe that goes without saying.

**Comment by koscinskic** [comment]
OOP would give us the tools to easily define and isolate each team's work, thus making integration easier in the future. We can see how each team develops their features this week and look into classifying multiple features into modules to streamline data transfer.

**Comment by lussierc** [comment]
I would recommend using OOP as well, especially since that is the standard for previous CS classes here at Allegheny. 

I have a little bit of experience with `.json` from an independent study I had last year and think it would work well for what we are trying to do and would probably recommend that, but I feel we could make `.csv` work well too. There are a number of packages we could use to interact with both file types.

**Comment by koscinskic** [comment]
Here is what I would like to propose we use a standardized .json format:

Key: Tuple ( List , List , List )
where each var represents the following:
GithubID / User : ( Commit List , Issue List , PR List )

I have not extensively looked at the commit objects for either PyGithub or PyDriller (Assuming they exist, otherwise we could create our own object), but I'm assuming those objects (Should they exist) would contain enough relevant information for this format to store all the data we would need for this project.

**Comment by koscinskic** [comment]
It's a tad bit late to propose this, but with the project starting to come together, would we be able to have a meeting once or twice a week to address integration and structure concerns? We could discuss meeting further in Slack, but I figured I would address it here as once does not currently exist.

**Comment by mcnultycollin** [comment]
I'm cool with that! If you want to suggest a time. My thursdays are the most open

**Comment by koscinskic** [comment]
Let's look to meet at 3:00 PM this Thursday in Alden. I'll see if I can get a hold of some people from Project Management and Evaluation so we can iron out the structure in one meeting.

**Comment by koscinskic** [comment]
It has been quite a while since this issue was opened, but I did originally determine that each method should have an associated Fast-API call attached to it. Seeing as the package has not been a topic of discussion for quite a while, are we going to proceed with an implementation involving Fast-API, or is it no longer necessary?

**Comment by carmop** [comment]
Hey guys, so I stayed in the lab and worked on a way to gather a lot of commit data from pydriller and organize it with the help of the TAs. After a whole lot of trying stuff out we figure out that converting pydriller data straight to .json is almost impossible bc of the way that the Commit object was defined by the people that made pydriller. So instead I wrote some code that unpacks a lot of the data from the Commit obj and that puts it into a list of dictionaries where we have the following:

 -hashes as strings, commit msgs as strings, 
 -commit author as a string, 
 -commit date as a datetime obj, 
 -whether it was a merge commit or not as a boolean value, 
 -lines added or removed as an int, 
 -complexity as an int, 
 -and methods as a list of strings which are the name of the methods in the file.

 So I am gonna continue this later and write these values into a database (some noSQL like mongoDB) since .json would not work (or it would but it would add a ton of complexity to the already complicated project). So the remainder of data gathering that I am not sure can be obtained through pydriller is issue tracker data and PR data, so when you guys work on gathering that data try to make it so we can put it into a database later on without changing much of the code.

**Comment by mcnultycollin** [comment]
nice! Which branch is this code in? I would be interested in checking it out.

**Comment by carmop** [comment]
It is on team-interactions-basic-CLI. most the code there is for the CLI my group is working but since there is no architect branch i pushed it there, it is on src/data_collection.py

**Comment by carmop** [comment]
I am reading about mongoDB because it might be the best way to make that data available for everyone to use so if I manage to integrate that I think it should be merged to the master-branch

**Comment by koscinskic** [comment]
How smooth do you think the transition to mongoDB will be, and do you believe it's necessary to switch? We had formerly proposed that all teams had their functions working with the .json format by the end of the lab week, so unless not much needs to be changed on the mining / processing end, this transition could be expensive in terms of time.

**Comment by koscinskic** [comment]
I suppose it does depend on how well everyone has made their modules conform to a parameterized fashion...

**Comment by mcnultycollin** [comment]
I am not especially familiar with mongo, but have heard good things. Would it just interact with the JSON file post-processing? If so, I imagine that it wouldn't be too difficult to implement.

**Comment by koscinskic** [comment]
Figured I would drop the structure we determined the other day in this issue. The PR for this structure is [here](https://github.com/GatorCogitate/cogitate_tool/pull/39).

cogitate_tool
| - data
|   | - contributor_data.json
| - tests
|   | - test_feature1_test.py
|   | - test_feature2_test.py
|   | - test_json-handler.py
| - src
|   | - json_handler.py
|   | - menu.py
|   | - miner.py
|   | - processing.py
| - .gitignore
| - .travis.yml
| - Pipfile
| - Pipfile.lock
| - README.md

**Comment by carmop** [comment]
So the idea after I did some research is to have the mongoDB as a way to easily query the json file because other wise we would not have an easy way to get specific info out of it. However I am still looking into how that is going to work, some other colleagues have told me that SQLite might do the queries better

**Comment by koscinskic** [comment]
SQLite is moderately intuitive from what little experience I have with it. It would most likely be a productive improvement if we could streamline the data alteration process as much as possible.

**Comment by koscinskic** [comment]
My apologies for the late notice, but if everyone here could briefly analyze all of the source code from their team's branch(es), we could determine how much work to allocate to refactoring and integration when we setup this week's schedule. Also, is everyone here still clear to meet tonight at 8:00 PM?

**Comment by noorbuchi** [comment]
Hi everyone! I have been trying to refactor my group's data processing module to work with the .json file template you've created and I have some questions and suggestions. I am specifically talking about the commits and the commit data that can be retrieved from Pydriller and not anything regarding issues or pull requests. In the .json file, you create a dictionary where usernames are keys and the values are dictionaries of lists. While this structure can work very well in getting some of the basic information such as commit hashes, it would be more challenging to get specific commit information such as lines added or removed. I also noticed that in the file `data_collection.py`, you store all of the commit data in a list of dictionaries where every item of the list is the information of a commit object rather than a specific user. My main question is, how do you plan on adding the data collected from `data_collection.py` into the .json file considering that they are structured differently and how would you modify the file to make this data more accessible? Additionally, do you think that storing the commit object from Pydriller in the .json file would be more appropriate than storing the hash of each commit?  My team plans on retrieving all of the commit data collected to make calculations that would then be added back to the .json file. For ease of access, I suggest that we add another key to individual dictionaries making the structure look something like this
```
"stephensonc": {
        "overall_metrics" : {
            "EMAIL": "",
            "COMMITS": 0,
            "ADDED": 0,
            "REMOVED": 0,
            "TOTAL": 0,
            "MODIFIED": 0,
            "RATIO": 0,
            "FILES": [],
            "FORMAT": []
        },
        "commits": [
            "commit hash 1",
            "commit hash 2",
            "commit hash 3"
        ],
        "issues": [
            "issue 1 to which stephensonc contributed",
            "issue 2 to which stephensonc contributed",
            "issue 3 to which stephensonc contributed"
        ],
        "pull_requests": [
            "PR 1 to which stephensonc contributed",
            "PR 2 to which stephensonc contributed",
            "PR 3 to which stephensonc contributed"
        ]
    }
```
I would appreciate any feedback on this suggestion and the questions mentioned above.

**Comment by koscinskic** [comment]
Having a specific overall metrics key with additional nested keys would be a good way to go about organizing that data. Having said, I believe my last push modified that format to expand "issues" and "pull requests" into additional categories. This won't have any effect on your implementation, but you will need to pull master and modify 'data_contributor_template' to add your proposed changes.

**Comment by koscinskic** [comment]
Also, the '.gitignore' in Master has an exclusion for said template, so you should be able to modify it without issue.

**Comment by noorbuchi** [comment]
@koscinskic can you please be specific about which commit you are referring to. Also, would you prefer that I make the changes to your branch or keep them in my branch which will be later merged?

**Comment by koscinskic** [comment]
Here is the file I pushed in my last merge with master: https://github.com/GatorCogitate/cogitate_tool/commit/b8737f1db255db03a79b61023aa1684dfb0195cf#diff-7e368a8393875176c9099b6e9e46702d

It would be safe to simply include it in your pull request to master. Alternatively, we could make another data-integration branch (not sure where the original went) and push it from there.

**Comment by noorbuchi** [comment]
@koscinskic thanks for including the merge. I've been working on refactoring our module to retrieve the collected data from the .json file but I'm getting an issue related to the `json-handler.py` file. specifically, it is saying that the file cannot be found in the directory `FileNotFoundError: [Errno 2] No such file or directory: './data/contributor_data_template.json'` . I think that this is due to a syntax error in the handler file where the directory should be `../data/` instead of `./data/` After changing it I stopped getting that error, but there was another error in the `data_collection.py` when writing on the .json file because the `commit_date` variable is not compatible with .json. I'm not sure if this issue tracker is responsible for this file but I wanted to bring to your attention some of the issues I'm facing.

**Comment by noorbuchi** [comment]
@koscinskic I have some updates on the previously mentioned issue of the directory not found. While `./` refers to the current directory, `../` refers to the one right before it. The `json_handler.py` file refers to the directory of `./`  as it is present in the master branch. This causes no issues when running the test suite because the test suite is run from the first level of the folder right outside of the `data` folder. However, when running a file from inside the `src` folder, this directory causes an issue because a folder named `data` cannot be found inside of `src`. I'm not sure how this would be solved, but I think that it is of high priority considering that it causes the test cases and the Travis build to fail.

**Comment by mcnultycollin** [comment]
Hello, I have noticed that lines_modified has been removed as a metric form data_collection, and I am curious why this is the case. The individual_metrics.py code still anticipates that this data will exist. 
Using the method @koscinskic and I wrote previously, we can retrieve modified lines per user no problem if we simply reinstate this in data_collection.py.

**Comment by noorbuchi** [comment]
@mcnultycollin Although having this data collected would be nice, our group does not take this data from the `data_collection` module. Instead, we calculate it after all user data have been collected.

**Comment by mcnultycollin** [comment]
@noorbuchi we will need to ensure that this is an accurate method for calculation. Please see the issue tracker I just opened so that we can go about evaluating things of this nature.

**Comment by koscinskic** [comment]
I'm probably a little late for the conversation, but using something along the lines of os.path.dirname(os.path.abspath(__file__)) should correct any directory navigation issues. Otherwise, after reviewing what is in the branch, I would assume that running pytest tests/_whatever_your_file_is_called_.py should resolve the issue as the default pytest command executes from root.

**Comment by koscinskic** [comment]
@mcnultycollin could you link the issue here where the data format is currently being discussed? (Both for personal reference and ease-of-access)

**Comment by lussierc** [comment]
@mcnultycollin Could you link the mentioned issue when you have a chance?

**Comment by koscinskic** [comment]
Today's laboratory session was rather chaotic (at least, I don't remember much what occurred outside of what I was focused on). Where do we currently stand in terms of the .json format? Are we adopting the structure proposed in individual_metrics utilizing RAW_DATA and INDIVIDUAL_CONTRIBUTIONS? Has this system been converted and fully integrated with .json? If so, what is the status of the PR associated with those changes?

**Comment by noorbuchi** [comment]
@koscinskic My team and I have been working on refactoring our code to match the structure that you've requested. Our [pull request](https://github.com/GatorCogitate/cogitate_tool/pull/35#discussion_r387453294) is almost ready with all of the changes. Please check it out and let us know if anything else is needed before merging.

**Comment by mcnultycollin** [comment]
@lussierc late but here's the issue i was referring to, which i'll be working on next few days.
 https://github.com/GatorCogitate/cogitate_tool/issues/59

**Comment by Jordan-A** [comment]
Here's an update on the `data_collection.py` refactored code. We just merged our pull request into the `master` branch. When possible merge master into your branches to get what was worked on. If you have any thoughts about our work please comment in our[ issue tracker](https://github.com/GatorCogitate/cogitate_tool/issues/12), @ us in this issue tracker, or message us in slack. Thanks!

**Comment by gkapfham** [comment]
What is the status of this issue? Any updates are appreciated!!

**Comment by noorbuchi** [comment]
@gkapfham I believe that this issue has been resolved and all agreed-upon changes were merged into the master branch. Unless there are any other questions, it can be closed.

**Comment by lussierc** [comment]
I would agree with @noorbuchi, I don’t think we need this issue now that everything has been merged. If further questions arise we can re-open the issue if necessary.

**Comment by gkapfham** [comment]
Great, that is what I thought! Can you please go ahead and close the issue? Thanks!
