### ISSUE TITLE
Team Interactions - Basic CLI Demo

### ISSUE THREAD

**Issue by johnsc1** [GatorCogitate/cogitate_tool#19]
This is the issue for Team Interactions Week 1 Demo - Basic Command Line Interface! 
These are the links @liux2 added our team's general issue: 
https://codeburst.io/building-beautiful-command-line-interfaces-with-python-26c7e1bb54df
https://docs.python-guide.org/scenarios/cli/

**We are now using Click to create the CLI.** [Here](https://click.palletsprojects.com/en/7.x/#documentation) is the Click documentation.

**Comment by liux2** [comment]
# Here are some simple examples for Python fire.

## 1. Hello World

```python
import fire

def hello(name):
  return 'Hello {name}!'.format(name=name)

if __name__ == '__main__':
  fire.Fire()
```


```python
pipenv run python eg1.py hello World
```

    Hello World!


**Or**

```python
import fire

def hello(name):
  return 'Hello {name}!'.format(name=name)

if __name__ == '__main__':
  fire.Fire(hello)
```


```python
pipenv run python eg2.py World
```

    Hello World!


So, the idea is to write different functions, and call the function from either terminal or main functions.

## 2. Grouping

Now, what if we want multiple functions, and even have a group of functions?

```python
import fire

class Calculator(object):

  def add(self, x, y):
    return x + y

  def multiply(self, x, y):
    return x * y

if __name__ == '__main__':
  fire.Fire(Calculator)
```


```python
pipenv run python eg3.py add 10 20
```

    30



```python
pipenv run python eg3.py multiply 10 20
```

    200


So, here the idea is we group functions by class, and we can call individual functions.

## 3. Trade-Offs

Our goal is to:

1. make the project simple
2. user can have more free choises, rather than our default calculations.

So, we need to have some interactive features for our CLI

### Advantage

Simple and easy, a ungraded version of argparse.

### Disadvantage

Does not have interactive interfaces. Have to use weight and parameters every time.

**Comment by johnsc1** [comment]
Based on the two articles in the top comment of this issue and this article, https://opensource.com/article/18/5/3-python-command-line-tools , I think the best command line tool we could use is click. It is the first CLI detailed in this article, and it is mentioned in the second article in the first comment. It seemed to address some of the limitations in other widely-used CLIs, plus it has great documentation and provides the user with help instructions very easily, so it is both developer and user friendly.

**Comment by liux2** [comment]
I think Click is a pretty good one.

**Comment by johnsc1** [comment]
Ok! We can start working on creating the basic framework so methods can be added asap!

**Comment by liux2** [comment]
According to [Python Doc](https://docs.python-guide.org/writing/structure/), I think we should structure our repo as follows:

```bash
.
|_ README.md
|_TODO.md
|_Pipfile
|_Pipfile.lock
|_License
|_scripts/
|      |_ name.sh *environmental setup or pipenv scripts
|_tests/
|      |_ test.py
|_src/
       |_ main.py
       |_model_1.py
       |_ model_2.py
```

Also, the license is based on the open-source projects we used in our project.

**Comment by liux2** [comment]
Just pushed it.

**Comment by liux2** [comment]
At this point, I think we should just use `argparse`, it has everything we need, and it is very easy to implement.

**Comment by johnsc1** [comment]
Now that argparse has been implemented, I will be working on our feature to identify code hoarders as well as testing that feature. Please let me know if I can help with anything else!

**Comment by johnsc1** [comment]
This is under #47 now as our main task is creating a full Command Line Interface.
