### ISSUE TITLE
Specifications of the project

### ISSUE THREAD

**Issue by bagashvilit** [GatorCogitate/cogitate_tool#26]
@gkapfham As a customer, would you like us to obtain data only from the `master` branch and ignore other active/inactive branches? This is something that we should discuss as a team, however, I believe that the customer's opinion would be helpful too.

**Comment by MaddyKapfhammer** [comment]
@bagashvilit this is a great question! I think that perhaps it is most important to obtain data from the `master` branch, but collecting data from active branches may also be useful in certain situations. I say focus on the `master` branch for now. In lab tomorrow each team will have time to meet with the customer to ask questions, so you should definitely bring this up then and hopefully we will have a more clear answer.

**Comment by bagashvilit** [comment]
@MaddyKapfhammer Thank you for the response. I also think that for now we can focus on `master` branch.

**Comment by noorbuchi** [comment]
@MaddyKapfhammer thank you for answering our question. @bagashvilit and I were having some difficulties gathering information from the repository. As of now, the program created doesn't just focus on the master branch, it also dismisses any merging of pull requests and does not count the lines added from the pull request. We are trying to find out whether this is a limitation of Pydriller and how we can possibly overcome it. Any feedback would be appreciated!

**Comment by schultzh** [comment]
This would be a great question to ask in our allotted time with the customer in lab tomorrow!

@noorbuchi Could you expand what you mean by the program not focusing on just master? Does it also pull from branches?

**Comment by gkapfham** [comment]
I agree with @schultzh that we should primarily focusing on the content that is merged to the master branch. With that said, there is one follow-on idea that I have: it might also be useful to characterize how frequently/how much code/documentation/tests a person writes that _does not_ ultimately make it into the master branch. What do you think @bagashvilit and @MaddyKapfhammer and @noorbuchi and @schultzh? Of course, we can discuss this further on Tuesday and then documentation and continue the conversation here as well. See you soon!

**Comment by noorbuchi** [comment]
Thank you @gkapfham for your feedback! I will try to address your suggestion while making some clarifications which @schultzh has asked about in a previous comment. We put this question up as an issue tracker because we are currently facing some difficulties with Pydriller that limit the scope of the line-count feature. If we choose to focus on the master branch of a repository (the only way we've been able to get the program to work for now), then only commits that directly changed or added to the branch will be counted. This will not count or credit authors of merged pull requests and instead will display the name of the person who merged the pull request. This seems like a limitation of Pydriller and we are trying to look further into its API to find a solution, we are also considering using PyGithub but we've encountered issues with that as well. As for the idea proposed in the previous comment, I think it is worth looking more into it mainly to answer the question "Is the code in unmerged pull requests or deleted branches a sign of productivity?" and I think the answer is more than just yes or no so we will have to discuss this as a team. I've also added a sample output of our feature when requesting data from our code of conduct repository. It is clear that not all contributors are displayed. You can also notice that there is an issue of duplication when displaying users' information due to perhaps committing from different devices. Any feedback would be appreciated.
```
Enter the path to the repo : https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-conduct
Username 	 + 	 - 	 Total
Gregory M. Kapfhammer 	 91 	 12 	 79
Xingbang Liu 	 110 	 102 	 8
devin spitalny 	 99 	 73 	 26
noorbuchi 	 68 	 25 	 43
Marisol Santa Cruz 	 37 	 21 	 16
Jordan-A 	 106 	 90 	 16
Thomas Cassidy 	 41 	 27 	 14
Noor Buchi 	 89 	 50 	 39
StringerJ 	 56 	 25 	 31
Christian Lussier 	 1 	 1 	 0
Pedro 	 11 	 11 	 0
Collin McNulty 	 1 	 1 	 0
Caden Koscinski 	 18 	 11 	 7
Jordan Byrne 	 5 	 5 	 0
Chris Stephenson 	 7 	 7 	 0
enpuyou 	 2 	 2 	 0
````

**Comment by MaddyKapfhammer** [comment]
It seems that this issue was addressed during the `Individual Metrics` team meeting with the customer today. The customer has stated that though this is a complex issue, he believes that information from the `master` branch is the most important to obtain. The `Individual Metrics` team is going to first create features that depend on the `master` branch, and will extend this to other branches if time allows.
