### ISSUE TITLE
Individual Metrics-Questions for the Customer

### ISSUE THREAD

**Issue by MaddyKapfhammer** [GatorCogitate/cogitate_tool#27]
Tomorrow in our lab session our team will have the opportunity to meet with the customer in order to ask questions about our current features, and features that should/will still be developed or clarify anything that we do not currently have information on. Perhaps we could add some questions to ask the customer in comments of this issue so that we are prepared for our meeting tomorrow.

**Comment by schultzh** [comment]
Some questions I would suggest: 

What data regarding lines of code would you like to see?
How would you like them to calculated?
Net/overall/should it include comments? 

Any other thoughts team?

**Comment by Jordan-A** [comment]
@schultzh I like the questions that you came up with! I think it would be useful to ask if he wants to see the individual metrics for an entire repository, all of the branches, or both the repository and branches.

**Comment by gkapfham** [comment]
These are all great questions @schultzh, I look forward to discussing them soon! It would also be great if others in the class, like @Jordan-A and @MaddyKapfhammer can think about what they would judge as being the most useful set of details to collect about this issue. Thanks!

Finally, if you would like, we can begin the discussion here. Alternatively, we can talk in person on Tuesday and then continue to have and document the conversation here. See you soon!

**Comment by Jordan-A** [comment]
Q & A Customer Transcript:

Question 1 - What data regarding lines of code specifically? 
A: Partly what we have 
- lines changed
- lines added
- lines deleted.
- Breakdown by file type. 10 lines of python, 10 lines of markdown code

- Lines changed counted as deletion and addition of code. Correct. If there's no way to report changed lines, it's okay to stick with lines added/deleted. Clarify this issue in the terminal. Many text editors have special symbol for change that's different from add/delete. There might be a way to figure it out. 

Question 2 - What's more valuable net lines or lines added/deleted:
- All equally equivalent. 

Question 3: - Net or added/changed lines should include comments.
- Yes!
- Concerns about people abusing this feature.
- Yes this has happened before. We should view comments as okay, but comments for the sake of comments violate the rules of the POSD. 
- Code ratios could be very useful. Ratios commits/add/changed/delete.

Question 4: Should we parse all comments to determine if it's a good or bad comments. 
- Yes, and it would be very useful! Don't know how to do this. 
- Do comments match a certain pattern, using natural language processing to build comment model.

Question 5: Should we create hierarchy of liens of code. Ex: List worth less than definition. Should characters on a line be relevant? 
- Learn towards no if it's syntactically correct. 

Question 6: Should blank lines count towards lines added? Should we parse the lines of the program for empty lines
- Okay for someone to add a blank line. 
- Ex: Student commits code that fails lint checks. Recommits after formatting and all lines are changed.
- Different comments for bash, script, and python file.

Question 7: See all commits for branches or main?
- Preference is master branch. 
- Branch not merged, don't care? 
- View is that if it's not merged into master branch it doesn't "count" because it's not a part of
the working tool
- TL: Ran out of time? Failing? Thinks branches or PR should count. Questions should be answered first before decision. Work was done for a purpose. "I'm not the customer"

Question 8: stop boards comment quality? 
-yes, score sentence complexity, repeats variable

**Comment by WonjoonC** [comment]
Will we have another meeting with the customer to ask questions for our features today?

**Comment by schultzh** [comment]
We will not be having a structured meeting with the customer today, however if you have specific questions make sure you come prepared to ask them!

**Comment by MaddyKapfhammer** [comment]
It seems like we have had many of our questions answered by the customer during our last lab session on 2/18/2020 and during lab today on 2/25/2020 for this reason I am going to close this issue for now. If any other questions arise, please feel free to reopen this issue and we can discuss questions and ask the customer for input.
