### ISSUE TITLE
Improve Travis CI Configuration

### ISSUE THREAD

**Issue by koscinskic** [GatorCogitate/cogitate_tool#30]
Based off of the feedback from the overall evaluation team, it appears as though we still need to implement the following features to ensure a comprehensive build:

- [x] Automated Linting and Formatting
- [x] Automated Code Coverage Check (Based on future expectation)
- [x] Automated PyTest Execution

I'm not aware of any specialized Travis team, but we should try to integrate these checks to prevent bad builds from being merge in the future.

**Comment by schultzh** [comment]
I set up the Travis config originally so I can continue to add these things. Thanks for bringing them to my attention!

**Comment by MaddyKapfhammer** [comment]
@schultzh do you think that it is necessary to start a Travis CI team (comprised of members from each team like the Software Architecture team) to work on adding these things? Or are these easy decisions and checks that you and the project managers can manage?

**Comment by schultzh** [comment]
I don't think a team is necessary. Once code cov and pytest are completed there should not be any other need to continue working in Travis CI.

**Comment by koscinskic** [comment]
Another question regarding Travis:

The feature I'm currently working on involves creating a github object using a user token and accessing the repository in question via that object. All of the code in question requires that repository to function, as do the test cases. Currently, I'm passing the token in as part of the command line argument, so there are no security breaches. However, when Travis inevitably runs the test cases automatically for the build, there won't be a token unless we hard-code it and introduce a security breach.

Assuming there is no way around requiring a key, we could create a Github account specific to the GatorCogitate organization and hide the key in the Travis environment variables using data obfuscation.

Let me know if this isn't how the PyGithub package works in the first place and therefore isn't an actionable issue.

**Comment by schultzh** [comment]
Could you explain in greater detail how this is related to Travis CI configuration?

**Comment by spitalnyd** [comment]
> I don't think a team is necessary. Once code cov and pytest are completed there should not be any other need to continue working in Travis CI.

I agree!! I feel like making a team might also further complicate things as well.

**Comment by schultzh** [comment]
I will be away from campus on and off for the next few days and will not have time to work on this issue in detail. @spitalnyd Would you or anyone in your team be willing to take this on?

**Comment by spitalnyd** [comment]
Of course I or one my team members can try to figure something out in our meeting tomorrow! We might need some details on things you were working on so we can get idea to help you out!

**Comment by spitalnyd** [comment]
> I will be away from campus on and off for the next few days and will not have time to work on this issue in detail. @spitalnyd Would you or anyone in your team be willing to take this on?

Of course I or one my team members can try to figure something out in our meeting tomorrow! We might need some details on things you were working on so we can get idea to help you out!

**Comment by enpuyou** [comment]
@spitalnyd This will be the top priority now since none of the other PRs can be merged without Travis CI being correctly set up. I think what @schultzh have are good, all you need to do is to change some of the paths so that they are pointing at the right place.

@koscinskic I don't think to make an account solely for the test is a good approach. And if all the codes/functions require access to the token, then there is probably already some information leakage going on within the functions. Another possible solution to try is to have an encrypted environment variable in Travis to hold the github token, and just let the test cases read from the environment variable

**Comment by schultzh** [comment]
@spitalnyd Thanks!! Yes, @enpuyou pointed out that all that needs done is adding paths. I waited to do this step because the software arc team has not yet standardized the structure and so there are no folders to create a path with. And if you look in the current Travis build for the PR you can see what else needs to be added in order to finish.

**Comment by koscinskic** [comment]
Since you can't create a repository object without a token, it doesn't particular matter how well you control information leakage since the token would have been required at _some_ point in order to make said repository object. Having said, I'm not particular concerned about information leakage, so I would propose following through on the environment variable solution.

**Comment by koscinskic** [comment]
I merely proposed making an account so it wouldn't have to be our token that we encrypt in the environment variables.

**Comment by schultzh** [comment]
@koscinskic If you would like to continue this discussion regarding informations leakage, tokens, and creating a GitHub account, could you please move it to another issue as it does not directly correlate to the configuration of Travis CI. Thanks!!

**Comment by koscinskic** [comment]
The problem here is that we want the token to be added to the Travis environmental variables, which I would think is part of the configuration unless it's done through the actual Travis tool online.

**Comment by stephensonc** [comment]
In order to add an environment variable to Travis, you have to have administrator access to Travis on this repository itself, and add the environment variable through the online Travis tool as Caden K has indicated.

**Comment by schultzh** [comment]
@koscinskic @stephensonc Okay! Let me or @spitalnyd know when you are ready to move forward with those environment variables.

**Comment by enpuyou** [comment]
@koscinskic @stephensonc @schultzh The encrypted environment variable in Travis should be an easy implementation. I would suggest creating a new branch off of master to work on this instead of directly committing to #31 since it seems a little bit stuck at this point, that way you guys don't have to wait for all the other configurations to be done to merge this into the master

**Comment by stephensonc** [comment]
The Improve/travis-ci branch in #31 has no merge conflicts with master, and the test environment is functioning properly. I would like to try to get this merged as quickly as possible so that we can ensure quality code is pushed to master in the future. 

The build is failing right now, but that is due to existing linter and test case problems present in the source code files that are currently in master, not the Travis CI build itself.
