### ISSUE TITLE
multiple `.json` files

### ISSUE THREAD

**Issue by bagashvilit** [GatorCogitate/cogitate_tool#75]
@koscinskic I had a suggestion, why don't we keep dictionary of raw data and dictoinary of individual metrics data in separate `.json` files instead of same file. I think, that having multiple `.json` files would avoid having triple nested dictionaries and would make it easier for my team to access the data we need and do calculation. Please, let me know your opinion as soon as possible.

**Comment by noorbuchi** [comment]
@bagashvilit @koscinskic I completely agree with this. I think that it would help structure things a lot better by making a file specific for the raw data, and a different file for individual metrics.

**Comment by koscinskic** [comment]
That seems like a reasonable approach, but I would be cautious altering the state of the data structure so close to the deadline. It's a simple fix, so it shouldn't be a problem. Is there a branch already open for this change?

**Comment by noorbuchi** [comment]
There is not an open branch for this just yet, but we can get those changes added very soon. I think that we should have the files uniformly named through all of the branches to prevent confusion. @bagashvilit @MaddyKapfhammer how would you like us to start working on this? Since this is an issue that affects both of our branches, do you think that we should create a new branch or just add it to one of ours? Please let me know as soon as you can so we can start the changes. Please keep in mind that this would require changes to the `data_collection.py` file as well as multiple test cases that need to access the data.

**Comment by bagashvilit** [comment]
@noorbuchi Since this is affecting both of us, and will require changes to the test cases, I think we should create new branch, what do you think?

**Comment by noorbuchi** [comment]
I think that would be the best approach, I will create a new branch soon and get these changes merged soon. Please let me know if you have any other suggestions for changes in that branch.

**Comment by noorbuchi** [comment]
@MaddyKapfhammer  @bagashvilit I just created the branch under the name `multiple_json_files` please feel free to make any changes needed.

**Comment by bagashvilit** [comment]
@noorbuchi Thank you for creating new branch, I'll take a look at that as soon as I can.

**Comment by noorbuchi** [comment]
@bagashvilit @MaddyKapfhammer I have a quick update, I've reworked all of the `data_collection.py` function. I think this is a great improvement and it allows for a more organized structure. I still have to fix any remaining linter issues in addition to reworking test cases.

**Comment by noorbuchi** [comment]
The changes were implemented and merged so this issue will be closed
